/**
 * PROTOTYPE FIXTURES — NOT PRODUCTION DATA.
 *
 * Written opinions and replies below are authored for the prototype. The names
 * are not real people and the helpful/reply counts are invented. They exist so
 * the Opinions and Discussion tabs can be reviewed with realistic density and
 * tone before real submissions exist.
 */

import type { Opinion, Reply, Sentiment } from "@/lib/types";

interface RawOpinion {
  id: string;
  name: string;
  initials: string;
  vote: Sentiment;
  text: string;
  time: string;
  helpful: number;
  replies: number;
  thread?: Reply[];
}

const RAW: Record<string, RawOpinion[]> = {
  /* ------------------------------------------- Entertainment & Brands */
  kalki2: [
    {
      id: "kal1",
      name: "Vikas Nambiar",
      initials: "VN",
      vote: "Positive",
      text: "Whatever else you think of it, nobody here is building worlds at this scale. The desert sequence alone is worth the ticket on a big screen.",
      time: "2 hours ago",
      helpful: 1420,
      replies: 88,
    },
    {
      id: "kal2",
      name: "Reshma Pillai",
      initials: "RP",
      vote: "Neutral",
      text: "First half is extraordinary. The second half explains itself three times and loses the tension it spent an hour building.",
      time: "6 hours ago",
      helpful: 1105,
      replies: 132,
      thread: [
        {
          name: "Vikas Nambiar",
          initials: "VN",
          text: "Agreed on the exposition. It reads like a cut made for a sequel rather than for this film.",
          time: "4 hours ago",
        },
      ],
    },
    {
      id: "kal3",
      name: "Joseph Mathew",
      initials: "JM",
      vote: "Positive",
      text: "Saw it in a full house at 9am. The room reacted to things a trailer cannot spoil, which is the whole point of going.",
      time: "1 day ago",
      helpful: 764,
      replies: 41,
    },
  ],
  panchayat5: [
    {
      id: "pan1",
      name: "Devika Rao",
      initials: "DR",
      vote: "Positive",
      text: "They resisted the temptation to make it bigger. Same courtyard, same silences, and the writing still trusts you to notice things on your own.",
      time: "3 days ago",
      helpful: 742,
      replies: 33,
    },
    {
      id: "pan2",
      name: "Harsh Vardhan",
      initials: "HV",
      vote: "Neutral",
      text: "Episodes four and five drag. Everything around them is as good as the show has ever been, so I am landing somewhere in the middle.",
      time: "4 days ago",
      helpful: 388,
      replies: 27,
      thread: [
        {
          name: "Devika Rao",
          initials: "DR",
          text: "Fair. The election subplot needed one fewer episode to breathe.",
          time: "3 days ago",
        },
      ],
    },
    {
      id: "pan3",
      name: "Ayesha Kabir",
      initials: "AK",
      vote: "Positive",
      text: "The last ten minutes earned the five seasons it took to get there. I have nothing analytical to add.",
      time: "5 days ago",
      helpful: 1104,
      replies: 41,
    },
  ],
  netflixin: [
    {
      id: "net1",
      name: "Farhan Sheikh",
      initials: "FS",
      vote: "Negative",
      text: "The mobile tier was the reason half my family had an account at all. Moving it up by nearly half while the catalogue shrinks is a hard sell.",
      time: "4 hours ago",
      helpful: 1980,
      replies: 143,
    },
    {
      id: "net2",
      name: "Ipshita Ghosh",
      initials: "IG",
      vote: "Neutral",
      text: "Prices go up, that is not news. What annoys me is finding out from a banner mid-episode rather than an email two weeks earlier.",
      time: "7 hours ago",
      helpful: 1122,
      replies: 61,
      thread: [
        {
          name: "Farhan Sheikh",
          initials: "FS",
          text: "This is the part that gets me too. The number is arguable; the communication is not.",
          time: "5 hours ago",
        },
      ],
    },
    {
      id: "net3",
      name: "Mohit Raina",
      initials: "MR",
      vote: "Negative",
      text: "Cancelled and moved to a quarterly rotation between three services. I suspect a lot of people are about to do the same arithmetic.",
      time: "1 day ago",
      helpful: 1436,
      replies: 88,
    },
  ],
  zeptoten: [
    {
      id: "zep1",
      name: "Ananya Bhalla",
      initials: "AB",
      vote: "Positive",
      text: "Paracetamol at 2am for a feverish toddler, delivered in nine minutes. I am not going to pretend that is not extraordinary.",
      time: "8 hours ago",
      helpful: 1240,
      replies: 96,
      thread: [
        {
          name: "Sohail Ansari",
          initials: "SA",
          text: "Nobody disputes the convenience. The question is what the person on the bike was asked to do to make nine minutes happen.",
          time: "6 hours ago",
        },
      ],
    },
    {
      id: "zep2",
      name: "Sohail Ansari",
      initials: "SA",
      vote: "Negative",
      text: "I rode for one of these apps for eleven months. Ten minutes is not a delivery promise, it is a target you break traffic rules to hit.",
      time: "12 hours ago",
      helpful: 1880,
      replies: 152,
    },
    {
      id: "zep3",
      name: "Kritika Menon",
      initials: "KM",
      vote: "Neutral",
      text: "Fine for groceries. Selling prescription-adjacent medicines on a ten-minute clock with no pharmacist in the loop is a different category of risk.",
      time: "1 day ago",
      helpful: 906,
      replies: 74,
    },
  ],

  /* ------------------------------------------------------------ Sports */
  t20squad: [
    {
      id: "t20_1",
      name: "Rajat Sekhri",
      initials: "RS",
      vote: "Negative",
      text: "Three specialist spinners on those surfaces is a plan for a different tournament. We have picked for the conditions we wish we were playing in.",
      time: "50 minutes ago",
      helpful: 2410,
      replies: 214,
      thread: [
        {
          name: "Priyanka Doshi",
          initials: "PD",
          text: "Two of those three bat at eight or better. It is a batting-depth decision dressed up as a spin decision.",
          time: "30 minutes ago",
        },
      ],
    },
    {
      id: "t20_2",
      name: "Priyanka Doshi",
      initials: "PD",
      vote: "Positive",
      text: "Finally a squad picked on strike rate rather than reputation. The two omissions are harsh and they are also correct.",
      time: "1 hour ago",
      helpful: 1985,
      replies: 178,
    },
    {
      id: "t20_3",
      name: "Manav Trivedi",
      initials: "MT",
      vote: "Neutral",
      text: "Squad looks fine. The XI is the actual problem and we will not see it until the warm-ups.",
      time: "3 hours ago",
      helpful: 1102,
      replies: 63,
    },
  ],
  impactplayer: [
    {
      id: "imp1",
      name: "Sandeep Rathore",
      initials: "SR",
      vote: "Negative",
      text: "I have watched genuine all-rounders lose their place to a specialist substitute for five seasons. The rule solved a problem nobody had.",
      time: "1 day ago",
      helpful: 1520,
      replies: 118,
    },
    {
      id: "imp2",
      name: "Leena Fernandes",
      initials: "LF",
      vote: "Neutral",
      text: "Scores are up, close finishes are up, ratings are up. All of that is true and it still makes the game slightly less interesting to think about.",
      time: "2 days ago",
      helpful: 984,
      replies: 87,
      thread: [
        {
          name: "Sandeep Rathore",
          initials: "SR",
          text: "This is the fairest summary I have read. It is entertaining and it is worse cricket.",
          time: "1 day ago",
        },
      ],
    },
  ],
  isleague: [
    {
      id: "isl1",
      name: "Debjit Sarkar",
      initials: "DS",
      vote: "Positive",
      text: "A closed league in football is not a league, it is a franchise business. This is the single most important thing the sport can do here.",
      time: "1 day ago",
      helpful: 1180,
      replies: 72,
    },
    {
      id: "isl2",
      name: "Nikita Verma",
      initials: "NV",
      vote: "Neutral",
      text: "Right idea. 2028 gives franchises two seasons to prepare, which is either sensible or a way to quietly let it die.",
      time: "2 days ago",
      helpful: 640,
      replies: 44,
    },
  ],
  olympicbid: [
    {
      id: "oly1",
      name: "Hemant Kulkarni",
      initials: "HK",
      vote: "Positive",
      text: "Hosting forces the infrastructure timeline in a way nothing else does. Every city that has done it got a decade of work in seven years.",
      time: "2 days ago",
      helpful: 940,
      replies: 88,
    },
    {
      id: "oly2",
      name: "Sarita Naidu",
      initials: "SN",
      vote: "Negative",
      text: "Show me the legacy plan for the venues before the bid, not after. That sentence is the entire history of Olympic overspend.",
      time: "3 days ago",
      helpful: 1360,
      replies: 124,
      thread: [
        {
          name: "Hemant Kulkarni",
          initials: "HK",
          text: "Reasonable. The draft does mention post-Games use but only in one paragraph, which tells you how much thought it got.",
          time: "2 days ago",
        },
      ],
    },
  ],

  /* -------------------------------------------------------- Technology */
  iphone18: [
    {
      id: "iph1",
      name: "Karan Bedi",
      initials: "KB",
      vote: "Negative",
      text: "Assembled here, taxed here, priced as though it flew in from Cupertino this morning. The local assembly story stopped being a consumer benefit years ago.",
      time: "3 hours ago",
      helpful: 2210,
      replies: 164,
      thread: [
        {
          name: "Meher Jain",
          initials: "MJ",
          text: "Assembly is not manufacturing. Almost none of the component value is local, so the price was never going to move.",
          time: "2 hours ago",
        },
      ],
    },
    {
      id: "iph2",
      name: "Meher Jain",
      initials: "MJ",
      vote: "Neutral",
      text: "The hardware is excellent and the price is indefensible. Both things have been true for four generations now.",
      time: "5 hours ago",
      helpful: 1340,
      replies: 92,
    },
    {
      id: "iph3",
      name: "Ravi Shanbhag",
      initials: "RS",
      vote: "Positive",
      text: "Kept my last one five years and it still gets updates. Amortised over that, the sticker price is not the number that matters.",
      time: "9 hours ago",
      helpful: 1088,
      replies: 137,
    },
  ],
  jioai: [
    {
      id: "jio1",
      name: "Aparna Sridhar",
      initials: "AS",
      vote: "Negative",
      text: "Switched on by default across every app I did not ask it to touch. Consent that you have to go and withdraw is not consent.",
      time: "5 hours ago",
      helpful: 2040,
      replies: 156,
    },
    {
      id: "jio2",
      name: "Bhaskar Rao",
      initials: "BR",
      vote: "Neutral",
      text: "The assistant is genuinely useful for recharges and bill queries in Hindi. The data terms are what I cannot get comfortable with.",
      time: "10 hours ago",
      helpful: 1120,
      replies: 88,
      thread: [
        {
          name: "Aparna Sridhar",
          initials: "AS",
          text: "That is the trap. It is good enough that opting out costs you something real.",
          time: "8 hours ago",
        },
      ],
    },
    {
      id: "jio3",
      name: "Tanya Kohli",
      initials: "TK",
      vote: "Positive",
      text: "My parents can now do things in the app that took me a phone call every month. That is worth something and it rarely gets counted.",
      time: "1 day ago",
      helpful: 780,
      replies: 104,
    },
  ],
  iplstream: [
    {
      id: "ipl1",
      name: "Aditya Shetty",
      initials: "AS",
      vote: "Negative",
      text: "Paid for the annual plan specifically for the season. Two overs into the super over the feed dropped to what looked like 240p and stayed there.",
      time: "6 hours ago",
      helpful: 2740,
      replies: 188,
      thread: [
        {
          name: "Nandita Bose",
          initials: "NB",
          text: "Same in Pune on fibre. It is not our connections — the CDN falls over in the last five overs when everyone tunes in.",
          time: "4 hours ago",
        },
      ],
    },
    {
      id: "ipl2",
      name: "Rahul Menon",
      initials: "RM",
      vote: "Neutral",
      text: "Latency is far better than last season and the multi-camera feed is genuinely good. Ad load during strategic timeouts is still absurd.",
      time: "1 day ago",
      helpful: 842,
      replies: 96,
    },
    {
      id: "ipl3",
      name: "Sania Kapoor",
      initials: "SK",
      vote: "Positive",
      text: "1080p with no stutter through the whole chase. Whatever is failing is not failing everywhere, which is worth saying in a thread like this.",
      time: "1 day ago",
      helpful: 508,
      replies: 121,
    },
  ],
  evprice: [
    {
      id: "ev1",
      name: "Girish Pattnaik",
      initials: "GP",
      vote: "Negative",
      text: "Bought in January. Three cuts later the same car is 2.4 lakh cheaper and my resale value went with it. No protection, no goodwill, nothing.",
      time: "1 day ago",
      helpful: 1620,
      replies: 143,
      thread: [
        {
          name: "Simran Ahluwalia",
          initials: "SA",
          text: "Every early adopter in every category has taken this hit. It is still bad practice to do it three times in five months.",
          time: "20 hours ago",
        },
      ],
    },
    {
      id: "ev2",
      name: "Simran Ahluwalia",
      initials: "SA",
      vote: "Positive",
      text: "The segment is finally priced where a middle-income family can actually consider it. That is the point of a price war.",
      time: "2 days ago",
      helpful: 1180,
      replies: 88,
    },
  ],

  /* --------------------------------- National & International Events */
  wc2026: [
    {
      id: "wc1",
      name: "Ishaan Mehra",
      initials: "IM",
      vote: "Negative",
      text: "Dynamic pricing on a World Cup ticket is how you turn the biggest event in sport into an auction. Half the group games are already out of reach.",
      time: "5 hours ago",
      helpful: 1740,
      replies: 128,
    },
    {
      id: "wc2",
      name: "Fatima Rizvi",
      initials: "FR",
      vote: "Neutral",
      text: "48 teams means more countries get a night they will never forget and more group games nobody will remember. Both are real.",
      time: "9 hours ago",
      helpful: 1080,
      replies: 96,
      thread: [
        {
          name: "Ishaan Mehra",
          initials: "IM",
          text: "This is the most honest take on expansion I have seen. It is a trade, not an upgrade.",
          time: "7 hours ago",
        },
      ],
    },
    {
      id: "wc3",
      name: "Neel Kapadia",
      initials: "NK",
      vote: "Positive",
      text: "Kick-offs land at a watchable hour here for once. After four World Cups of 12:30am group games I will take it.",
      time: "1 day ago",
      helpful: 812,
      replies: 44,
    },
  ],
  chandrayaan4: [
    {
      id: "ch1",
      name: "Dr. Lalitha Menon",
      initials: "LM",
      vote: "Positive",
      text: "Sample return is a genuinely different order of difficulty from a landing. If this works it changes what we can credibly propose next.",
      time: "10 hours ago",
      helpful: 1980,
      replies: 74,
    },
    {
      id: "ch2",
      name: "Sameer Dutta",
      initials: "SD",
      vote: "Neutral",
      text: "Fully behind it. I would still like the mission budget published in the same detail as the launch date gets publicised.",
      time: "1 day ago",
      helpful: 640,
      replies: 88,
    },
  ],
  mumbaiflood: [
    {
      id: "mum1",
      name: "Yusuf Merchant",
      initials: "YM",
      vote: "Negative",
      text: "Third time this season. The drainage programme has been funded in four consecutive budgets and my lane still becomes a canal by 9am.",
      time: "40 minutes ago",
      helpful: 3120,
      replies: 246,
      thread: [
        {
          name: "Rachana Pai",
          initials: "RP",
          text: "The utilisation figures for that programme are public and they are well under half. That is the story nobody is running.",
          time: "20 minutes ago",
        },
      ],
    },
    {
      id: "mum2",
      name: "Rachana Pai",
      initials: "RP",
      vote: "Negative",
      text: "Suburban services suspended at peak with no announcement until people were already on the platform. The response is worse than the rain.",
      time: "2 hours ago",
      helpful: 2480,
      replies: 174,
    },
    {
      id: "mum3",
      name: "Anwar Shaikh",
      initials: "AS",
      vote: "Neutral",
      text: "Ward staff were out at 5am and the pumping stations did run. The failure is upstream of the people doing the actual work.",
      time: "4 hours ago",
      helpful: 1340,
      replies: 92,
    },
  ],
  cop31: [
    {
      id: "cop1",
      name: "Dr. Nandini Iyer",
      initials: "NI",
      vote: "Negative",
      text: "Count the money that is actually new and the headline number falls by more than half. We have now done this at four consecutive summits.",
      time: "4 days ago",
      helpful: 1220,
      replies: 96,
    },
    {
      id: "cop2",
      name: "Peter Nongrum",
      initials: "PN",
      vote: "Neutral",
      text: "A weak deal that exists beats a strong deal that does not. I would rather argue about the accounting than start again from nothing.",
      time: "5 days ago",
      helpful: 860,
      replies: 74,
    },
  ],

  /* -------------------------------------------------- National Politics */
  bihar26: [
    {
      id: "bih1",
      name: "Ranjeet Kumar",
      initials: "RK",
      vote: "Negative",
      text: "Both alliances have had a year to settle seats and neither can. If you cannot organise yourselves, why would I trust you with a state?",
      time: "2 hours ago",
      helpful: 2140,
      replies: 186,
    },
    {
      id: "bih2",
      name: "Sushmita Jha",
      initials: "SJ",
      vote: "Neutral",
      text: "For the first time in my adult life the campaign is actually about jobs and migration rather than the usual arithmetic. That is progress even if the rest is a mess.",
      time: "6 hours ago",
      helpful: 1480,
      replies: 122,
      thread: [
        {
          name: "Ranjeet Kumar",
          initials: "RK",
          text: "Agreed on the framing. Ask me again after the first week of actual campaigning.",
          time: "4 hours ago",
        },
      ],
    },
  ],
  oneelection: [
    {
      id: "one1",
      name: "Adv. Meenakshi Rau",
      initials: "MR",
      vote: "Negative",
      text: "Curtailing sitting assembly terms to force synchronisation is the part nobody defends on merit. The savings argument does not touch it.",
      time: "5 hours ago",
      helpful: 1920,
      replies: 168,
    },
    {
      id: "one2",
      name: "Prashant Bhalerao",
      initials: "PB",
      vote: "Positive",
      text: "We are in campaign mode somewhere in this country every month of every year. Governance stops for it. One cycle is worth the transition pain.",
      time: "9 hours ago",
      helpful: 1640,
      replies: 194,
      thread: [
        {
          name: "Adv. Meenakshi Rau",
          initials: "MR",
          text: "The permanent-campaign problem is real. Solving it by shortening mandates voters already gave is the wrong instrument.",
          time: "7 hours ago",
        },
      ],
    },
    {
      id: "one3",
      name: "Zoya Hameed",
      initials: "ZH",
      vote: "Neutral",
      text: "I want to see the cost study that is being cited. Every side quotes a number and none of them link the source.",
      time: "1 day ago",
      helpful: 940,
      replies: 62,
    },
  ],
  delimitation: [
    {
      id: "del1",
      name: "Ramya Subramaniam",
      initials: "RS",
      vote: "Negative",
      text: "States that did what national policy asked for fifty years would lose seats for having succeeded. Say that sentence out loud and the problem is obvious.",
      time: "9 hours ago",
      helpful: 2260,
      replies: 208,
    },
    {
      id: "del2",
      name: "Ajay Pandey",
      initials: "AP",
      vote: "Neutral",
      text: "One person one vote is not a small principle either. There is no clean answer here, only a negotiated one, and pretending otherwise is not helping.",
      time: "14 hours ago",
      helpful: 1580,
      replies: 176,
      thread: [
        {
          name: "Ramya Subramaniam",
          initials: "RS",
          text: "This is the honest version of the other side and I wish it were the one being argued in public.",
          time: "11 hours ago",
        },
      ],
    },
  ],
  oppalliance: [
    {
      id: "opp1",
      name: "Devendra Sahu",
      initials: "DS",
      vote: "Negative",
      text: "Three deadlines missed. At some point the inability to agree is itself the information voters are being given.",
      time: "1 day ago",
      helpful: 1420,
      replies: 118,
    },
    {
      id: "opp2",
      name: "Farida Begum",
      initials: "FB",
      vote: "Neutral",
      text: "Coalitions are slow everywhere. I would rather they take another month than announce something that collapses in October.",
      time: "2 days ago",
      helpful: 880,
      replies: 74,
    },
  ],

  /* ------------------------------------------------ Government Policies */
  upicharge: [
    {
      id: "upi1",
      name: "Nikhil Bhardwaj",
      initials: "NB",
      vote: "Negative",
      text: "I run a tea stall. Half my customers pay two rupees at a time by scanning the code. If there is any charge at all on that, I go back to cash and so does everyone around me.",
      time: "1 day ago",
      helpful: 1840,
      replies: 96,
      thread: [
        {
          name: "Ritika Sood",
          initials: "RS",
          text: "The clarification says small-value payments are out of scope, but the paper does not define small clearly. That vagueness is the real problem.",
          time: "22 hours ago",
        },
      ],
    },
    {
      id: "upi2",
      name: "Ritika Sood",
      initials: "RS",
      vote: "Neutral",
      text: "Someone is paying for this infrastructure today and it is the banks. I would rather have an honest, capped charge on large merchants than a system that quietly degrades.",
      time: "1 day ago",
      helpful: 903,
      replies: 71,
    },
    {
      id: "upi3",
      name: "Sandeep Kulkarni",
      initials: "SK",
      vote: "Negative",
      text: "Every consultation paper in the last five years has ended with the consumer paying. I have no reason to believe this one is different.",
      time: "2 days ago",
      helpful: 1265,
      replies: 58,
    },
    {
      id: "upi4",
      name: "Fatima Q.",
      initials: "FQ",
      vote: "Positive",
      text: "Charging large merchants who process crores a month is not the same as charging me. The headline is doing a lot of work the document does not support.",
      time: "2 days ago",
      helpful: 612,
      replies: 104,
    },
  ],
  fourday: [
    {
      id: "fd1",
      name: "Tanvi Malhotra",
      initials: "TM",
      vote: "Positive",
      text: "Six months into a compressed week at our firm. Output is flat, attrition halved, and Fridays are no longer a performance of being busy.",
      time: "9 hours ago",
      helpful: 2088,
      replies: 164,
    },
    {
      id: "fd2",
      name: "Suresh Iyengar",
      initials: "SI",
      vote: "Neutral",
      text: "Works for desk work. I run a two-shift plant — a fifth day off means machines idle or a sixth hire. The pilot should say which sectors it is for.",
      time: "1 day ago",
      helpful: 1344,
      replies: 121,
    },
    {
      id: "fd3",
      name: "Arvind Pillai",
      initials: "AP",
      vote: "Negative",
      text: "Every flexible-hours pilot I have seen ended with the same work in fewer hours and no change in pay. Show me the compensation clause first.",
      time: "2 days ago",
      helpful: 1502,
      replies: 109,
      thread: [
        {
          name: "Tanvi Malhotra",
          initials: "TM",
          text: "Ours kept pay flat and headcount flat. It is possible — it just needs to be written down rather than promised.",
          time: "1 day ago",
        },
      ],
    },
  ],
  gigrules: [
    {
      id: "gig1",
      name: "Mukesh Yadav",
      initials: "MY",
      vote: "Positive",
      text: "Eleven years riding and this is the first time anyone has written down that we are owed something. I will take it and keep arguing for the rest.",
      time: "1 day ago",
      helpful: 1680,
      replies: 94,
    },
    {
      id: "gig2",
      name: "Anita Kurien",
      initials: "AK",
      vote: "Neutral",
      text: "A fund with no published disbursement mechanism is an announcement, not a benefit. Ask me again when someone has actually been paid from it.",
      time: "2 days ago",
      helpful: 1240,
      replies: 108,
      thread: [
        {
          name: "Mukesh Yadav",
          initials: "MY",
          text: "Not wrong. Half the schemes I have been told about never reached anyone I know.",
          time: "1 day ago",
        },
      ],
    },
  ],
  nep: [
    {
      id: "nep1",
      name: "Prof. Latha Venkatesh",
      initials: "LV",
      vote: "Positive",
      text: "The multidisciplinary credit structure is the first genuinely student-shaped reform I have taught under. Implementation is uneven; the direction is right.",
      time: "3 days ago",
      helpful: 1084,
      replies: 92,
    },
    {
      id: "nep2",
      name: "Sanjay Deshmukh",
      initials: "SD",
      vote: "Negative",
      text: "Two states, two entirely different rollouts, and a student who moves between them loses a year. A national framework that is not national is paperwork.",
      time: "4 days ago",
      helpful: 1247,
      replies: 116,
      thread: [
        {
          name: "Prof. Latha Venkatesh",
          initials: "LV",
          text: "Credit transfer is the weakest part of the whole thing and it was flagged at drafting stage. Fair criticism.",
          time: "3 days ago",
        },
      ],
    },
  ],

  /* ------------------------------------------------------- Politicians */
  "office-finance": [
    {
      id: "fin1",
      name: "Rohan Deshpande",
      initials: "RD",
      vote: "Neutral",
      text: "Capex delivery genuinely is ahead of schedule and that deserves credit. The personal tax relief was announced twice and delivered zero times.",
      time: "12 hours ago",
      helpful: 1420,
      replies: 108,
    },
    {
      id: "fin2",
      name: "Swati Bhagat",
      initials: "SB",
      vote: "Negative",
      text: "Salaried filers have absorbed every adjustment for four years while corporate rates held. At some point that is a choice, not a constraint.",
      time: "1 day ago",
      helpful: 1860,
      replies: 142,
      thread: [
        {
          name: "Rohan Deshpande",
          initials: "RD",
          text: "The revenue mix data backs this up. It is the clearest single criticism of the record.",
          time: "20 hours ago",
        },
      ],
    },
  ],
  "office-railways": [
    {
      id: "rail1",
      name: "Bhavesh Solanki",
      initials: "BS",
      vote: "Positive",
      text: "The new rakes are a genuine step change and I say that as someone who complained for a decade. Punctuality on my route is another conversation.",
      time: "1 day ago",
      helpful: 1120,
      replies: 86,
    },
    {
      id: "rail2",
      name: "Lakshmi Narayanan",
      initials: "LN",
      vote: "Negative",
      text: "Launching premium services while the ordinary network slips is a choice about who counts. My train has been late on 19 of 22 journeys this year.",
      time: "2 days ago",
      helpful: 1740,
      replies: 132,
      thread: [
        {
          name: "Bhavesh Solanki",
          initials: "BS",
          text: "The rake is fine; the pathing is the problem, and pathing is a capacity decision, not a hardware one.",
          time: "1 day ago",
        },
      ],
    },
  ],
  "office-cm-karnataka": [
    {
      id: "cm1",
      name: "Deepa Srinivasan",
      initials: "DS",
      vote: "Negative",
      text: "Roads, water, metro. Three things, one city, four years. I do not have a fourth complaint because those three are enough.",
      time: "8 hours ago",
      helpful: 2340,
      replies: 198,
    },
    {
      id: "cm2",
      name: "Basavaraj Hittalmani",
      initials: "BH",
      vote: "Positive",
      text: "Everyone here rates a state government on one city. The rural water schemes in my district actually work now and nobody writes about that.",
      time: "1 day ago",
      helpful: 1420,
      replies: 164,
      thread: [
        {
          name: "Deepa Srinivasan",
          initials: "DS",
          text: "This is a fair correction and the dashboard should probably separate urban and rural delivery.",
          time: "20 hours ago",
        },
      ],
    },
  ],
  "office-opposition": [
    {
      id: "lop1",
      name: "Nusrat Ali",
      initials: "NA",
      vote: "Neutral",
      text: "Attendance is up and the interventions are better researched. The walkouts still hand the government a free afternoon every time.",
      time: "1 day ago",
      helpful: 1180,
      replies: 118,
    },
    {
      id: "lop2",
      name: "Vivek Chaturvedi",
      initials: "VC",
      vote: "Negative",
      text: "Disruption is the only tool that gets coverage, and that is a media failure as much as a political one. It is still not working.",
      time: "2 days ago",
      helpful: 1360,
      replies: 142,
    },
  ],

  /* ---------------------------------------------------------- Colleges */
  iitb: [
    {
      id: "iitb1",
      name: "Aniket Ranade",
      initials: "AR",
      vote: "Positive",
      text: "Day one and two went faster than last year in our department. The slowdown reporting does not match what I watched happen in the room.",
      time: "1 day ago",
      helpful: 704,
      replies: 48,
      thread: [
        {
          name: "Pooja Iyer",
          initials: "PI",
          text: "Day one is always fine. It is day six onward where the gap between departments shows up, and that is what people mean by slowdown.",
          time: "22 hours ago",
        },
      ],
    },
    {
      id: "iitb2",
      name: "Pooja Iyer",
      initials: "PI",
      vote: "Neutral",
      text: "Median holding steady while the top decile pulls away is not a good season, it is a stratified one. The headline number hides that completely.",
      time: "2 days ago",
      helpful: 618,
      replies: 55,
    },
  ],
  iima: [
    {
      id: "iima1",
      name: "Rhea Chandrasekhar",
      initials: "RC",
      vote: "Negative",
      text: "The loan maths only works if you assume the median placement holds for twenty years. Anyone who graduated into 2020 knows how that assumption ages.",
      time: "2 days ago",
      helpful: 984,
      replies: 71,
    },
    {
      id: "iima2",
      name: "Nitin Saraf",
      initials: "NS",
      vote: "Neutral",
      text: "Fee is up 11%; the needs-based waiver pool is up more than that in absolute terms. Both numbers were in the same release and only one travelled.",
      time: "3 days ago",
      helpful: 712,
      replies: 64,
      thread: [
        {
          name: "Rhea Chandrasekhar",
          initials: "RC",
          text: "The waiver covers a few dozen students. The fee covers everyone. Those are not comparable magnitudes.",
          time: "2 days ago",
        },
      ],
    },
  ],
  "du-fyup": [
    {
      id: "du1",
      name: "Ishaan Gokhale",
      initials: "IG",
      vote: "Negative",
      text: "A fourth year of fees and rent so that a masters becomes one year instead of two. For most families that is a deferral, not a saving.",
      time: "2 days ago",
      helpful: 1142,
      replies: 94,
    },
    {
      id: "du2",
      name: "Dr. Payal Mistry",
      initials: "PM",
      vote: "Positive",
      text: "The research year is the point. Students entering our PhD programme from the four-year track arrive able to run a project unsupervised.",
      time: "3 days ago",
      helpful: 906,
      replies: 62,
    },
    {
      id: "du3",
      name: "Nikhil Sawant",
      initials: "NS",
      vote: "Neutral",
      text: "Good structure, badly sequenced. Foreign universities recognised the degree before half our own postgraduate departments updated their rules.",
      time: "4 days ago",
      helpful: 788,
      replies: 51,
    },
  ],
  nitt: [
    {
      id: "nitt1",
      name: "Sathish Ramalingam",
      initials: "SR",
      vote: "Positive",
      text: "The new lab block is genuinely better equipped than anything I used in my first two years. Whoever pushed that through deserves the credit.",
      time: "5 days ago",
      helpful: 412,
      replies: 22,
    },
    {
      id: "nitt2",
      name: "Divya Ganesan",
      initials: "DG",
      vote: "Neutral",
      text: "Labs and library are excellent. Hostel occupancy is still three to a two-person room in first year, which is what people actually live with.",
      time: "6 days ago",
      helpful: 386,
      replies: 29,
    },
  ],

  /* ------------------------------------------------------------- Exams */
  neet: [
    {
      id: "neet1",
      name: "Rohit Menon",
      initials: "RM",
      vote: "Negative",
      text: "I sat for this exam. One of the sets going around a coaching group two days earlier matched what we got, question for question in the chemistry section. I have no way to prove that now, which is exactly the problem.",
      time: "3 days ago",
      helpful: 2412,
      replies: 138,
      thread: [
        {
          name: "Sneha Iyer",
          initials: "SI",
          text: "Did anyone in your centre file a written complaint? The committee is only considering documented submissions.",
          time: "3 days ago",
        },
        {
          name: "Rohit Menon",
          initials: "RM",
          text: "Two of us did, on the 8th. No acknowledgement number yet.",
          time: "2 days ago",
        },
      ],
    },
    {
      id: "neet2",
      name: "Dr. Sneha Iyer",
      initials: "SI",
      vote: "Neutral",
      text: "Worth separating two questions: whether a leak happened somewhere, and whether it was wide enough to move the national merit list. The committee has confirmed only the first.",
      time: "4 days ago",
      helpful: 1890,
      replies: 121,
    },
    {
      id: "neet3",
      name: "Aman Gupta",
      initials: "AG",
      vote: "Negative",
      text: "Same cycle every year. Allegations, a committee, a press note, and by August nobody remembers. I want a re-exam date, not a four-member panel.",
      time: "5 days ago",
      helpful: 2056,
      replies: 144,
      thread: [
        {
          name: "Karthik S.",
          initials: "KS",
          text: "A re-exam for 24 lakh candidates on the basis of unverified screenshots would be its own disaster. Let the panel finish.",
          time: "4 days ago",
        },
      ],
    },
    {
      id: "neet4",
      name: "Priya Nair",
      initials: "PN",
      vote: "Neutral",
      text: "My score is fine and I still want a re-test. A result that nobody trusts is worth very little on paper, whatever my rank says.",
      time: "6 days ago",
      helpful: 1198,
      replies: 87,
    },
    {
      id: "neet5",
      name: "Vikram Deshpande",
      initials: "VD",
      vote: "Negative",
      text: "Sceptical of this dashboard too, for what it is worth. The people angry enough to vote are the ones who show up. It means 78% is 78% of the people here, not of the country.",
      time: "2 weeks ago",
      helpful: 1402,
      replies: 161,
      thread: [
        {
          name: "Dr. Sneha Iyer",
          initials: "SI",
          text: "Agreed, and the caption under the chart says exactly that. Self-selected samples skew toward the aggrieved.",
          time: "2 weeks ago",
        },
      ],
    },
  ],
  "upsc-key": [
    {
      id: "upsc1",
      name: "Anubhav Sinha",
      initials: "AS",
      vote: "Negative",
      text: "Nine disputed questions is roughly nine marks, which at this level is several hundred ranks. Publishing the reasoning costs them nothing.",
      time: "7 hours ago",
      helpful: 1980,
      replies: 148,
      thread: [
        {
          name: "Kavita Rangan",
          initials: "KR",
          text: "Other commissions publish subject-expert notes for rejected objections. There is no argument for not doing it beyond habit.",
          time: "5 hours ago",
        },
      ],
    },
    {
      id: "upsc2",
      name: "Kavita Rangan",
      initials: "KR",
      vote: "Neutral",
      text: "Two of the nine genuinely have defensible alternatives. The other seven are aspirants hoping. Both groups are filing the same objection form.",
      time: "11 hours ago",
      helpful: 1420,
      replies: 112,
    },
  ],
  cuet: [
    {
      id: "cuet1",
      name: "Divya Rajagopal",
      initials: "DR",
      vote: "Negative",
      text: "Results landed after two of the three universities I applied to had closed their first list. The delay did not just cost time, it cost a seat.",
      time: "6 days ago",
      helpful: 1620,
      replies: 104,
    },
    {
      id: "cuet2",
      name: "Tarun Bhattacharya",
      initials: "TB",
      vote: "Neutral",
      text: "Resolved is doing heavy lifting as a status here. Results are out; the admission calendar that broke around them has not been fixed for next year.",
      time: "7 days ago",
      helpful: 918,
      replies: 63,
    },
  ],
  gate: [
    {
      id: "gate1",
      name: "Anushka Wagle",
      initials: "AW",
      vote: "Negative",
      text: "Four numerical questions in the algorithms set had no clean answer within the given precision. That is not difficulty, that is a paper-setting error.",
      time: "3 days ago",
      helpful: 1094,
      replies: 96,
      thread: [
        {
          name: "Praveen Kumar",
          initials: "PK",
          text: "Two of those already have objections filed. The response window closes tomorrow if anyone else wants to raise them.",
          time: "2 days ago",
        },
      ],
    },
    {
      id: "gate2",
      name: "Praveen Kumar",
      initials: "PK",
      vote: "Neutral",
      text: "Aptitude was lighter than usual, the core section heavier. Whether it was harder depends entirely on which half you prepared for.",
      time: "3 days ago",
      helpful: 742,
      replies: 58,
    },
    {
      id: "gate3",
      name: "Rakesh Bhoir",
      initials: "RB",
      vote: "Positive",
      text: "Fairest paper in three years from where I sat. Rewarded understanding over memorised formula sheets, which is the point of the exam.",
      time: "4 days ago",
      helpful: 618,
      replies: 34,
    },
  ],

  /* ---------------------------------------------------- Career Streams */
  "ms-abroad": [
    {
      id: "ms1",
      name: "Aditi Ramaswamy",
      initials: "AR",
      vote: "Negative",
      text: "Went in 2024 on a two-year work-rights assumption that was cut to one while I was mid-degree. Forty lakh of debt against twelve months to find a sponsor.",
      time: "4 hours ago",
      helpful: 2640,
      replies: 212,
      thread: [
        {
          name: "Rohan Kalra",
          initials: "RK",
          text: "This is why the dashboard needs to split by intake year. Advice from a 2021 cohort is worse than useless now.",
          time: "2 hours ago",
        },
      ],
    },
    {
      id: "ms2",
      name: "Rohan Kalra",
      initials: "RK",
      vote: "Neutral",
      text: "Still worth it for a funded research programme. Almost never worth it for a self-funded taught masters at current fees and current visa rules.",
      time: "9 hours ago",
      helpful: 2110,
      replies: 168,
    },
    {
      id: "ms3",
      name: "Shalini Prabhu",
      initials: "SP",
      vote: "Positive",
      text: "Did mine part-funded, stayed, and I am three years in with permanent residence. It is harder than it was, not impossible, and the difference matters.",
      time: "1 day ago",
      helpful: 1340,
      replies: 146,
    },
  ],
  "mba-roi": [
    {
      id: "mba1",
      name: "Kunal Sabharwal",
      initials: "KS",
      vote: "Negative",
      text: "Tier-two, 26 lakh in fees, and a role I could have reached in two years without leaving. The brochure medians are not from my batch.",
      time: "6 hours ago",
      helpful: 2280,
      replies: 186,
    },
    {
      id: "mba2",
      name: "Ira Bhandari",
      initials: "IB",
      vote: "Positive",
      text: "Career switch from engineering to product, doubled comp in eighteen months. The degree is a switching cost, not a salary multiplier, and it worked as that.",
      time: "12 hours ago",
      helpful: 1860,
      replies: 154,
      thread: [
        {
          name: "Kunal Sabharwal",
          initials: "KS",
          text: "This is the right framing. If you are not switching function or geography the maths is very hard to justify now.",
          time: "9 hours ago",
        },
      ],
    },
    {
      id: "mba3",
      name: "Zaid Farooqui",
      initials: "ZF",
      vote: "Neutral",
      text: "The average is meaningless in this category. Post the tier-wise split or the number is actively misleading people into loans.",
      time: "1 day ago",
      helpful: 1420,
      replies: 98,
    },
  ],
  "cse-glut": [
    {
      id: "cse1",
      name: "Harini Balaji",
      initials: "HB",
      vote: "Negative",
      text: "Our branch has 480 seats where it had 180 four years ago. The recruiters visiting are the same ones, in the same numbers, with fewer roles.",
      time: "3 hours ago",
      helpful: 2740,
      replies: 224,
    },
    {
      id: "cse2",
      name: "Vivek Chandran",
      initials: "VC",
      vote: "Neutral",
      text: "Cyclical, probably. That is cold comfort if your graduating year happens to sit at the bottom of the cycle.",
      time: "8 hours ago",
      helpful: 1640,
      replies: 132,
      thread: [
        {
          name: "Harini Balaji",
          initials: "HB",
          text: "Cyclical is what everyone said in 2001 and 2009 too. The people in those batches still lost three years.",
          time: "6 hours ago",
        },
      ],
    },
    {
      id: "cse3",
      name: "Sristi Panda",
      initials: "SP",
      vote: "Positive",
      text: "Tier-three college, no campus drive, got in through an open qualifier. The expansion is why I had a route at all. That should count for something.",
      time: "1 day ago",
      helpful: 1180,
      replies: 108,
    },
  ],
  "govt-vs-private": [
    {
      id: "gov1",
      name: "Pallavi Deshpande",
      initials: "PD",
      vote: "Neutral",
      text: "Four years preparing, cleared nothing, joined private at 24. I do not regret trying and I would not tell anyone to give it more than three attempts.",
      time: "1 day ago",
      helpful: 1920,
      replies: 168,
      thread: [
        {
          name: "Anand Kulkarni",
          initials: "AK",
          text: "Three attempts is the most useful concrete advice in this whole thread.",
          time: "20 hours ago",
        },
      ],
    },
    {
      id: "gov2",
      name: "Anand Kulkarni",
      initials: "AK",
      vote: "Positive",
      text: "Twelve years in, pension intact, and I have never once worried about a layoff cycle. Ceiling is real; so is sleeping properly.",
      time: "2 days ago",
      helpful: 1640,
      replies: 124,
    },
  ],

  /* -------------------------------------------------------- Food & Dining */
  "delivery-fees": [
    { id: "df1", name: "Nikhil Bhardwaj", initials: "NB", vote: "Negative", text: "A 240-rupee biryani reached 389 at checkout. Platform fee, handling fee, packaging, surge. None of that was on the menu card I was looking at.", time: "40 minutes ago", helpful: 2840, replies: 196 },
    { id: "df2", name: "Kritika Menon", initials: "KM", vote: "Negative", text: "The restaurant near me now hands you a card asking you to call direct. When the merchant is actively routing around the platform, the platform has lost the plot.", time: "3 hours ago", helpful: 2210, replies: 148, thread: [ { name: "Ritika Sood", initials: "RS", text: "Half the small places I order from do this now. It is the clearest signal on how the split actually feels to them.", time: "2 hours ago" } ] },
    { id: "df3", name: "Ananya Bhalla", initials: "AB", vote: "Neutral", text: "Somebody is paying the rider, and it was never really the restaurant. I would rather see one honest delivery charge than five invented line items.", time: "7 hours ago", helpful: 1480, replies: 92 },
  ],
  "cloud-kitchens": [
    { id: "ck1", name: "Snehal Vaze", initials: "SV", vote: "Negative", text: "Four listings, four brand names, four sets of photos. One kitchen, which I only found out because the bill printed a different name than the app.", time: "4 hours ago", helpful: 1940, replies: 132 },
    { id: "ck2", name: "Ritu Bansal", initials: "RB", vote: "Negative", text: "I cannot walk in and look at the place. That is the entire safety mechanism I have used my whole life, and delivery-only quietly removed it.", time: "9 hours ago", helpful: 1620, replies: 108, thread: [ { name: "Anita Kurien", initials: "AK", text: "Which is exactly why the operating kitchen's licence number should sit on every listing. It is a database field, not a reform.", time: "6 hours ago" } ] },
    { id: "ck3", name: "Anita Kurien", initials: "AK", vote: "Neutral", text: "Plenty of good cloud kitchens exist and this drive will hurt them alongside the bad ones. Publish the ratings and let people choose.", time: "1 day ago", helpful: 1140, replies: 76 },
  ],
  "street-food-licensing": [
    { id: "sf1", name: "Prakash Meena", initials: "PM", vote: "Positive", text: "My father ran a cart for twenty years. A licence, a water source and a bin is not an unreasonable ask, and it protects the honest vendors most.", time: "8 hours ago", helpful: 1380, replies: 94 },
    { id: "sf2", name: "Anwar Shaikh", initials: "AS", vote: "Negative", text: "The fee is two weeks of margin and the vending zone is a kilometre from where the customers are. That is not regulation, it is removal.", time: "1 day ago", helpful: 1720, replies: 128, thread: [ { name: "Prakash Meena", initials: "PM", text: "The zoning is the real problem, not the licence. Fix the zones and most of the objection disappears.", time: "20 hours ago" } ] },
    { id: "sf3", name: "Yusuf Merchant", initials: "YM", vote: "Neutral", text: "Everyone wants clean street food and nobody wants the street food to go. The drive has not yet shown it can do both.", time: "1 day ago", helpful: 1060, replies: 71 },
  ],
  "millet-menus": [
    { id: "mm1", name: "Dr. Lalitha Menon", initials: "LM", vote: "Positive", text: "Genuinely better for anyone watching their blood sugar, and it took a policy push to get restaurants to bother. I will take the win.", time: "2 days ago", helpful: 780, replies: 48 },
    { id: "mm2", name: "Bhavesh Solanki", initials: "BS", vote: "Negative", text: "Ninety rupees more than the same dish with rice, for a grain that costs less. The health framing is doing a lot of pricing work.", time: "3 days ago", helpful: 1140, replies: 86 },
    { id: "mm3", name: "Divya Ganesan", initials: "DG", vote: "Neutral", text: "The ragi dosa at my usual place is excellent. The millet risotto at the chain down the road is an apology in a bowl. It depends entirely on whether they tried.", time: "3 days ago", helpful: 920, replies: 62 },
  ],

  /* --------------------------------------------------- Controversies */
  blrmetro: [
    {
      id: "blr1",
      name: "Deepa Srinivasan",
      initials: "DS",
      vote: "Negative",
      text: "I moved to this corridor in 2021 on the assumption the line would open by 2023. Three revised dates later I still spend ninety minutes each way on a bus.",
      time: "5 hours ago",
      helpful: 2310,
      replies: 132,
    },
    {
      id: "blr2",
      name: "Girish K.",
      initials: "GK",
      vote: "Negative",
      text: "The trains are physically sitting in the depot. Whatever the bottleneck is, it is not rolling stock any more, and nobody will say plainly what it is.",
      time: "11 hours ago",
      helpful: 1874,
      replies: 97,
      thread: [
        {
          name: "Ananya Rao",
          initials: "AR",
          text: "Signalling certification, per the last board note. Which is exactly the kind of thing that should be in a public dashboard rather than a PDF.",
          time: "8 hours ago",
        },
      ],
    },
    {
      id: "blr3",
      name: "Ananya Rao",
      initials: "AR",
      vote: "Neutral",
      text: "Frustrated, but I would rather they certify the signalling properly than open on a political deadline. Say so honestly and I will wait.",
      time: "1 day ago",
      helpful: 906,
      replies: 54,
    },
  ],
  "deepfake-ads": [
    {
      id: "df1",
      name: "Sunita Kaul",
      initials: "SK",
      vote: "Negative",
      text: "My father put money into a scheme because he saw a face he has trusted on television for thirty years say it was safe. He is 71. That is the whole harm.",
      time: "2 hours ago",
      helpful: 3240,
      replies: 268,
      thread: [
        {
          name: "Arjun Vaidya",
          initials: "AV",
          text: "Reported four of these last month. Two came back up under a new page within a day. Takedown is not the mechanism that will fix this.",
          time: "1 hour ago",
        },
      ],
    },
    {
      id: "df2",
      name: "Arjun Vaidya",
      initials: "AV",
      vote: "Negative",
      text: "The ads are paid placements. Somebody accepted money, ran a KYC check, and approved them. That is not a moderation failure, it is a sales one.",
      time: "6 hours ago",
      helpful: 2680,
      replies: 194,
    },
    {
      id: "df3",
      name: "Nivedita Ram",
      initials: "NR",
      vote: "Neutral",
      text: "Detection genuinely is hard at this volume. Ad-buyer verification is not hard at all, and that is where the rule should land.",
      time: "1 day ago",
      helpful: 1420,
      replies: 118,
    },
  ],
  "coaching-safety": [
    {
      id: "cs1",
      name: "Ritu Bansal",
      initials: "RB",
      vote: "Negative",
      text: "My daughter's batch of 90 sat in a basement with one staircase. We paid 1.8 lakh for that room. The sanction for it existed on paper.",
      time: "10 hours ago",
      helpful: 2860,
      replies: 208,
    },
    {
      id: "cs2",
      name: "Prakash Meena",
      initials: "PM",
      vote: "Negative",
      text: "Sealing notices after the fact are not enforcement, they are publicity. The inspection was due every year and did not happen for six.",
      time: "1 day ago",
      helpful: 2140,
      replies: 156,
      thread: [
        {
          name: "Ritu Bansal",
          initials: "RB",
          text: "And the centres reopen two streets away under a new registration. Parents have no way to check any of this.",
          time: "20 hours ago",
        },
      ],
    },
    {
      id: "cs3",
      name: "Snehal Vaze",
      initials: "SV",
      vote: "Neutral",
      text: "A public register of sanctioned capacity and last inspection date would do more than any number of sealing drives. It is a database, not a reform.",
      time: "1 day ago",
      helpful: 1580,
      replies: 94,
    },
  ],
  ainews: [
    {
      id: "ai1",
      name: "Sudeep Ranganathan",
      initials: "SR",
      vote: "Negative",
      text: "A byline is an accountability mechanism, not a credit line. If nobody can be called and asked why a paragraph is wrong, it should not carry a name.",
      time: "12 hours ago",
      helpful: 1310,
      replies: 118,
      thread: [
        {
          name: "Meghana Iyer",
          initials: "MI",
          text: "This is the strongest version of the argument. The question is not authorship, it is who picks up the phone.",
          time: "9 hours ago",
        },
      ],
    },
    {
      id: "ai2",
      name: "Meghana Iyer",
      initials: "MI",
      vote: "Neutral",
      text: "We already publish agency copy under a desk byline and nobody objects. Machine-assisted drafting with a named editor is closer to that than to fabrication.",
      time: "16 hours ago",
      helpful: 884,
      replies: 71,
    },
    {
      id: "ai3",
      name: "Joel Fernandes",
      initials: "JF",
      vote: "Negative",
      text: "Disclose the tool in the footer and the problem mostly goes away. The resistance to a one-line disclosure tells you what the actual concern is.",
      time: "1 day ago",
      helpful: 736,
      replies: 52,
    },
  ],
};

export const OPINIONS: Opinion[] = Object.entries(RAW).flatMap(
  ([topicId, list]) => list.map((o) => ({ ...o, topicId })),
);

export function opinionsFor(topicId: string): Opinion[] {
  return OPINIONS.filter((o) => o.topicId === topicId);
}
