import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is generated by Next and uses triple-slash references.
    // `.next-build` is where `npm run build` lands — see distDir in
    // next.config.ts. Without it here, linting walks the compiled bundle and
    // reports twenty thousand problems in code nobody wrote.
    ignores: [
      ".next/**",
      ".next-build/**",
      "node_modules/**",
      "out/**",
      "next-env.d.ts",
    ],
  },
];

export default eslintConfig;
