/**
 * Flat config, native.
 *
 * `eslint-config-next` v16 ships a real flat config and exports it directly.
 * This file used to wrap it in `FlatCompat`, which exists to translate a
 * legacy `.eslintrc` into flat form — feeding it something that is already
 * flat made ESLint walk a config object that contains itself and die with
 * "Converting circular structure to JSON". The compat shim and its two
 * `__dirname` incantations are gone with it.
 */

import coreWebVitals from "eslint-config-next/core-web-vitals";
import typescript from "eslint-config-next/typescript";

const eslintConfig = [
  ...coreWebVitals,
  ...typescript,
  {
    /**
     * Two React 19 rules, demoted to warnings rather than turned off.
     *
     * `set-state-in-effect` fires sixteen times across seventeen files, and
     * almost every one is the legitimate case: syncing to something outside
     * React that cannot be read during render — a media query, the theme in
     * localStorage, the Supabase session, a toast timer. The rule is aimed at
     * a real footgun (an effect that sets state derived from props, causing a
     * second render), and some of these may well be that. Working out which is
     * a job worth doing deliberately, not a refactor to fold into a
     * dependency bump while the UI is being rebuilt.
     *
     * Warning rather than off, so they stay on screen and get fixed rather
     * than forgotten. `npm run lint` passes; `npm run lint -- --max-warnings 0`
     * is the stricter gate to turn on once they are worked through.
     */
    rules: {
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/exhaustive-deps": "warn",
    },
  },
  {
    // next-env.d.ts is generated by Next and uses triple-slash references.
    // `.next-build` is where `npm run build` lands — see distDir in
    // next.config.ts. Without it here, linting walks the compiled bundle and
    // reports twenty thousand problems in code nobody wrote.
    //
    // `.claude` holds vendored Claude Code skill scripts: CommonJS tooling
    // that happens to live in the repo rather than source this project ships.
    ignores: [
      ".next/**",
      ".next-build/**",
      "node_modules/**",
      "out/**",
      "next-env.d.ts",
      ".claude/**",
    ],
  },
];

export default eslintConfig;
