-- =============================================================================
-- Reference data — GENERATED. Do not edit by hand.
--
-- Written by `npm run db:gen-reference` from:
--   src/lib/places.ts        the places tree
--   src/lib/taxonomy.ts      the topic categories
--   src/lib/ask/taxonomy.ts  the three Ask areas
--   src/lib/ask/verification.ts  the kinds of proof
--   src/lib/demographics.ts  the occupation vocabulary
--   src/lib/facets.ts        the fallback question sets
--
-- Change the TypeScript, re-run the command, commit the new migration. Editing
-- this file instead means the next regeneration silently reverts you.
--
-- Contains no users, no votes, no opinions and no engagement figures: these are
-- facts about the product, not about people (AGENTS.md §7).
-- =============================================================================

-- 36 places, parents first so the self-FK resolves in one statement.
insert into public.places (id, label, short, level, parent_id, sort_order) values
  ('worldwide', 'Worldwide', 'Worldwide', 'world'::public.place_level, null, 0),
  ('india', 'India', 'India', 'country'::public.place_level, 'worldwide', 1),
  ('andhra-pradesh', 'Andhra Pradesh', 'AP', 'state'::public.place_level, 'india', 2),
  ('assam', 'Assam', 'Assam', 'state'::public.place_level, 'india', 3),
  ('bihar', 'Bihar', 'Bihar', 'state'::public.place_level, 'india', 4),
  ('delhi', 'Delhi NCR', 'Delhi', 'state'::public.place_level, 'india', 5),
  ('goa', 'Goa', 'Goa', 'state'::public.place_level, 'india', 6),
  ('gujarat', 'Gujarat', 'Gujarat', 'state'::public.place_level, 'india', 7),
  ('ahmedabad', 'Ahmedabad', 'Ahmedabad', 'city'::public.place_level, 'gujarat', 8),
  ('haryana', 'Haryana', 'Haryana', 'state'::public.place_level, 'india', 9),
  ('himachal-pradesh', 'Himachal Pradesh', 'Himachal', 'state'::public.place_level, 'india', 10),
  ('manali', 'Manali', 'Manali', 'city'::public.place_level, 'himachal-pradesh', 11),
  ('karnataka', 'Karnataka', 'Karnataka', 'state'::public.place_level, 'india', 12),
  ('bengaluru', 'Bengaluru', 'Bengaluru', 'city'::public.place_level, 'karnataka', 13),
  ('kerala', 'Kerala', 'Kerala', 'state'::public.place_level, 'india', 14),
  ('alappuzha', 'Alappuzha', 'Alappuzha', 'city'::public.place_level, 'kerala', 15),
  ('madhya-pradesh', 'Madhya Pradesh', 'MP', 'state'::public.place_level, 'india', 16),
  ('maharashtra', 'Maharashtra', 'Maharashtra', 'state'::public.place_level, 'india', 17),
  ('mumbai', 'Mumbai', 'Mumbai', 'city'::public.place_level, 'maharashtra', 18),
  ('pune', 'Pune', 'Pune', 'city'::public.place_level, 'maharashtra', 19),
  ('odisha', 'Odisha', 'Odisha', 'state'::public.place_level, 'india', 20),
  ('punjab', 'Punjab', 'Punjab', 'state'::public.place_level, 'india', 21),
  ('rajasthan', 'Rajasthan', 'Rajasthan', 'state'::public.place_level, 'india', 22),
  ('jaipur', 'Jaipur', 'Jaipur', 'city'::public.place_level, 'rajasthan', 23),
  ('tamil-nadu', 'Tamil Nadu', 'Tamil Nadu', 'state'::public.place_level, 'india', 24),
  ('chennai', 'Chennai', 'Chennai', 'city'::public.place_level, 'tamil-nadu', 25),
  ('trichy', 'Tiruchirappalli', 'Trichy', 'city'::public.place_level, 'tamil-nadu', 26),
  ('telangana', 'Telangana', 'Telangana', 'state'::public.place_level, 'india', 27),
  ('hyderabad', 'Hyderabad', 'Hyderabad', 'city'::public.place_level, 'telangana', 28),
  ('uttarakhand', 'Uttarakhand', 'Uttarakhand', 'state'::public.place_level, 'india', 29),
  ('nainital', 'Nainital', 'Nainital', 'city'::public.place_level, 'uttarakhand', 30),
  ('uttar-pradesh', 'Uttar Pradesh', 'UP', 'state'::public.place_level, 'india', 31),
  ('agra', 'Agra', 'Agra', 'city'::public.place_level, 'uttar-pradesh', 32),
  ('lucknow', 'Lucknow', 'Lucknow', 'city'::public.place_level, 'uttar-pradesh', 33),
  ('west-bengal', 'West Bengal', 'West Bengal', 'state'::public.place_level, 'india', 34),
  ('kolkata', 'Kolkata', 'Kolkata', 'city'::public.place_level, 'west-bengal', 35)
on conflict (id) do update set
  label = excluded.label,
  short = excluded.short,
  level = excluded.level,
  parent_id = excluded.parent_id,
  sort_order = excluded.sort_order;

insert into public.categories (id, label, short, blurb, reserved, sort_order) values
  ('entertainment', 'Entertainment', 'Entertainment', 'Films, series, music and live shows people argue about.', false, 0),
  ('brands', 'Brands', 'Brands', 'Consumer companies, judged on price, quality and how they treat you.', false, 1),
  ('sports', 'Sports', 'Sports', 'Teams, tournaments, selections and the calls that decide them.', false, 2),
  ('technology', 'Technology', 'Technology', 'Launches, gadgets, platforms and the companies behind them.', false, 3),
  ('events', 'National & International Events', 'Events', 'Summits, ceremonies, disasters and moments the world watches.', false, 4),
  ('national-politics', 'National Politics', 'Politics', 'Elections, alliances, legislation and the political weather.', false, 5),
  ('policies', 'Government Policies', 'Policies', 'Rules, schemes and proposals, and how they land in practice.', false, 6),
  ('politicians', 'Politicians', 'Politicians', 'Individual public figures, judged on record rather than party.', false, 7),
  ('colleges', 'Colleges', 'Colleges', 'Institutions rated by the students who actually attend them.', false, 8),
  ('exams', 'Exams', 'Exams', 'Papers, conduct, results and everything that goes wrong with them.', false, 9),
  ('careers', 'Career Streams', 'Careers', 'Degrees and paths, weighed by the people a few years ahead of you.', false, 10),
  ('food', 'Food & Dining', 'Food', 'Restaurants, delivery, street food and what it costs to eat out.', false, 11),
  ('places', 'Places & Travel', 'Places', 'Hotels, monuments and destinations, rated by people who went.', false, 12),
  ('controversies', 'Controversies', 'Controversies', 'Live disputes where the facts are still being established.', false, 13),
  ('other', 'Something else', 'Other', 'For subjects that fit none of the above. Yours to define.', true, 14)
on conflict (id) do update set
  label = excluded.label,
  short = excluded.short,
  blurb = excluded.blurb,
  reserved = excluded.reserved,
  sort_order = excluded.sort_order;

insert into public.ask_categories (id, label, short, blurb, examples, sort_order) values
  ('career'::public.ask_category, 'Career & jobs', 'Career', 'Job offers, software careers, interviews, switches and higher studies.', array['Should I accept this offer, or hold out for the other one?', 'Frontend, backend, cloud, data or DevOps — which fits my profile?', 'Is an MBA after engineering worth the two years?'], 0),
  ('college'::public.ask_category, 'Colleges', 'College', 'Choosing a college, a programme, placements, fees and campus life.', array['College A or College B for this branch?', 'Is this programme worth the fees given the placement record?', 'What is the student experience actually like?'], 1),
  ('exam'::public.ask_category, 'Exams', 'Exam', 'Preparation plans, timelines, mocks, targets and whether to attempt.', array['Can I realistically prepare for CAT while working full time?', 'Coaching or self-study, given where I am starting from?', 'Should I attempt this year, or postpone by one cycle?'], 2)
on conflict (id) do update set
  label = excluded.label,
  short = excluded.short,
  blurb = excluded.blurb,
  examples = excluded.examples,
  sort_order = excluded.sort_order;

-- The evidence itself is never stored on a credential. These rows describe what
-- may be offered and what the resulting badge is allowed to claim.
insert into public.proof_kinds (id, category, evidence_label, evidence_category, public_label, not_verified, weight) values
  ('employment'::public.proof_type, 'career'::public.ask_category, 'Work email or employee ID', 'Employer-issued identity', 'Current employment verified', 'Does not confirm seniority, compensation or tenure length.', 0),
  ('experience-letter'::public.proof_type, 'career'::public.ask_category, 'Experience or relieving letter', 'Employer-issued experience document', 'Previous employment verified', 'Does not confirm the scope or quality of the work performed.', 2),
  ('linkedin'::public.proof_type, 'career'::public.ask_category, 'LinkedIn profile', 'Professional profile, cross-checked', 'LinkedIn employment matched', 'Self-reported history beyond the matched role is not checked.', 3),
  ('portfolio'::public.proof_type, 'career'::public.ask_category, 'Portfolio or GitHub', 'Published work', 'Published work reviewed', 'Volume of output is not a measure of judgement.', 4),
  ('student-id'::public.proof_type, 'college'::public.ask_category, 'Student ID or college email', 'Institution-issued identity', 'Current student verified', 'Does not confirm marks, branch standing or placement status.', 0),
  ('degree'::public.proof_type, 'college'::public.ask_category, 'Degree certificate', 'Institution-issued award', 'Degree verified', 'Does not confirm class, grade or specialisation performance.', 1),
  ('alumni'::public.proof_type, 'college'::public.ask_category, 'Alumni email', 'Institution-controlled alumni domain', 'Alumni status verified', 'Does not confirm how current their campus knowledge is.', 2),
  ('scorecard'::public.proof_type, 'exam'::public.ask_category, 'Scorecard', 'Examination-body result document', 'Score verified', 'A score is not evidence of the method that produced it.', 1),
  ('rank-card'::public.proof_type, 'exam'::public.ask_category, 'Rank card', 'Examination-body rank document', 'Rank verified', 'Ranks are cycle-specific and do not transfer across years.', 0),
  ('admission-letter'::public.proof_type, 'exam'::public.ask_category, 'Admission letter', 'Institution-issued admission document', 'Admission from this exam verified', 'Does not confirm they completed the programme.', 2)
on conflict (id) do update set
  category = excluded.category,
  evidence_label = excluded.evidence_label,
  evidence_category = excluded.evidence_category,
  public_label = excluded.public_label,
  not_verified = excluded.not_verified,
  weight = excluded.weight;

insert into public.occupations (label, counts_in_breakdowns, sort_order) values
  ('Student', true, 0),
  ('Working professional', true, 1),
  ('Self-employed or business owner', true, 2),
  ('Parent or guardian', true, 3),
  ('Educator', true, 4),
  ('Retired', true, 5),
  ('Prefer not to say', false, 6)
on conflict (label) do update set
  counts_in_breakdowns = excluded.counts_in_breakdowns,
  sort_order = excluded.sort_order;

insert into public.facet_sets (id, label) values
  ('film', 'film'),
  ('series', 'series'),
  ('brand', 'brand'),
  ('sports', 'sports'),
  ('gadget', 'gadget'),
  ('platform', 'platform'),
  ('event', 'event'),
  ('national-politics', 'national-politics'),
  ('policy', 'policy'),
  ('politician', 'politician'),
  ('college', 'college'),
  ('exam', 'exam'),
  ('career', 'career'),
  ('food', 'food'),
  ('place', 'place'),
  ('controversy', 'controversy'),
  ('general', 'general')
on conflict (id) do update set label = excluded.label;

-- The category-level fallback question sets. A topic gets a *copy* of one of
-- these (see public.apply_facet_set), so editing the library later never
-- rewrites a question people have already answered.
insert into public.facet_set_facets (set_id, key, label, prompt, position) values
  ('film', 'story', 'Story & screenplay', 'How was the writing?', 0),
  ('film', 'acting', 'Performances', 'How did the cast do?', 1),
  ('film', 'music', 'Music & songs', 'Did the soundtrack land?', 2),
  ('film', 'visuals', 'Cinematography & VFX', 'How did it look?', 3),
  ('film', 'value', 'Worth the ticket', 'Would you tell a friend to watch it in a theatre?', 4),
  ('series', 'writing', 'Writing', 'How is the writing this season?', 0),
  ('series', 'pacing', 'Pacing', 'Does it hold its rhythm?', 1),
  ('series', 'cast', 'Performances', 'How is the cast?', 2),
  ('series', 'ending', 'Payoff', 'Did the season earn its ending?', 3),
  ('brand', 'value', 'Value for money', 'Is the price fair for what you get?', 0),
  ('brand', 'quality', 'Product quality', 'How does it hold up in use?', 1),
  ('brand', 'service', 'Customer service', 'How were you treated when something went wrong?', 2),
  ('brand', 'trust', 'Trust', 'Would you buy from them again?', 3),
  ('sports', 'performance', 'Team performance', 'How are they actually playing?', 0),
  ('sports', 'leadership', 'Captaincy & coaching', 'Are the calls being made well?', 1),
  ('sports', 'selection', 'Selection', 'Is the right side being picked?', 2),
  ('sports', 'entertainment', 'Watchability', 'Is it good to watch?', 3),
  ('sports', 'officiating', 'Officiating', 'Were the decisions sound?', 4),
  ('gadget', 'value', 'Value for money', 'Is it worth the asking price?', 0),
  ('gadget', 'build', 'Build & design', 'How does the hardware feel?', 1),
  ('gadget', 'performance', 'Performance', 'Does it do the job well?', 2),
  ('gadget', 'battery', 'Battery & reliability', 'Does it last?', 3),
  ('gadget', 'software', 'Software & updates', 'How is the software side?', 4),
  ('platform', 'reliability', 'Reliability', 'Does it work when you need it?', 0),
  ('platform', 'pricing', 'Pricing', 'Is what you pay reasonable?', 1),
  ('platform', 'privacy', 'Privacy & data use', 'Are you comfortable with how they use your data?', 2),
  ('platform', 'support', 'Support', 'Can you get a real answer from them?', 3),
  ('event', 'organisation', 'Organisation', 'How well was it run?', 0),
  ('event', 'safety', 'Public safety', 'Were people kept safe?', 1),
  ('event', 'coverage', 'Media coverage', 'Was the reporting fair?', 2),
  ('event', 'impact', 'Lasting impact', 'Will it matter in a year?', 3),
  ('national-politics', 'direction', 'Direction of governance', 'Is the country heading the right way on this?', 0),
  ('national-politics', 'economy', 'Economic handling', 'How is the economic side being managed?', 1),
  ('national-politics', 'transparency', 'Transparency', 'Is enough being disclosed?', 2),
  ('national-politics', 'tone', 'Public discourse', 'How is this being talked about?', 3),
  ('policy', 'intent', 'Intent', 'Is the underlying goal sound?', 0),
  ('policy', 'implementation', 'Implementation', 'Is it being rolled out well?', 1),
  ('policy', 'beneficiaries', 'Who benefits', 'Who does this actually help?', 2),
  ('policy', 'clarity', 'Communication', 'Was it explained clearly?', 3),
  ('policy', 'timing', 'Timing', 'Is now the right moment for this?', 4),
  ('politician', 'integrity', 'Integrity', 'Do you trust how they conduct themselves?', 0),
  ('politician', 'delivery', 'Delivery on promises', 'Have they done what they said?', 1),
  ('politician', 'communication', 'Communication', 'How do they explain their decisions?', 2),
  ('politician', 'accessibility', 'Accessibility', 'Are they reachable to people in their constituency?', 3),
  ('college', 'teaching', 'Teaching quality', 'How is the actual teaching?', 0),
  ('college', 'placements', 'Placements', 'Do outcomes match the reputation?', 1),
  ('college', 'facilities', 'Campus & hostel', 'How is day-to-day life on campus?', 2),
  ('college', 'fees', 'Fees vs value', 'Is the fee justified?', 3),
  ('college', 'culture', 'Student life', 'How is the culture and support?', 4),
  ('exam', 'difficulty', 'Difficulty & fairness', 'Was the paper fair?', 0),
  ('exam', 'conduct', 'Conduct & integrity', 'Was it run cleanly?', 1),
  ('exam', 'results', 'Results & timeliness', 'Were results handled properly?', 2),
  ('exam', 'syllabus', 'Syllabus alignment', 'Did it match what was prescribed?', 3),
  ('exam', 'grievance', 'Grievance handling', 'Were objections dealt with?', 4),
  ('career', 'roi', 'Return on investment', 'Was it worth the money and years?', 0),
  ('career', 'demand', 'Job market demand', 'Is there real demand right now?', 1),
  ('career', 'quality', 'Course quality', 'Did the programme teach you anything useful?', 2),
  ('career', 'worklife', 'Work-life outcome', 'How is life on the other side?', 3),
  ('career', 'advice', 'Would you recommend it', 'Would you tell someone to take this path today?', 4),
  ('food', 'taste', 'Taste', 'How was the food itself?', 0),
  ('food', 'value', 'Value for money', 'Was it worth what you paid?', 1),
  ('food', 'consistency', 'Consistency', 'Is it the same every visit?', 2),
  ('food', 'hygiene', 'Hygiene', 'How did the place look and feel?', 3),
  ('food', 'return', 'Would you go back', 'Are you returning?', 4),
  ('place', 'experience', 'The visit itself', 'Was it worth going?', 0),
  ('place', 'value', 'Value for money', 'Was it worth what it cost you?', 1),
  ('place', 'crowding', 'Crowds & queues', 'How busy was it when you went?', 2),
  ('place', 'upkeep', 'Upkeep & cleanliness', 'How well is the place looked after?', 3),
  ('place', 'access', 'Getting there & around', 'How easy was it to reach and navigate?', 4),
  ('place', 'return', 'Would you go back', 'Would you return, or send a friend?', 5),
  ('controversy', 'credibility', 'Credibility of the claims', 'How believable is the allegation so far?', 0),
  ('controversy', 'response', 'Institutional response', 'How have those responsible reacted?', 1),
  ('controversy', 'media', 'Media handling', 'Has the coverage been proportionate?', 2),
  ('controversy', 'accountability', 'Accountability so far', 'Has anyone actually been held to account?', 3),
  ('general', 'quality', 'Overall quality', 'How good is it?', 0),
  ('general', 'value', 'Worth it', 'Is it worth the time, money or attention?', 1),
  ('general', 'trust', 'Trust', 'Would you rely on it?', 2),
  ('general', 'recommend', 'Would you recommend it', 'Would you tell someone else about it?', 3)
on conflict (set_id, key) do update set
  label = excluded.label,
  prompt = excluded.prompt,
  position = excluded.position;

insert into public.facet_set_options (facet_id, key, label, tone, position)
select f.id, v.key, v.label, v.tone, v.position
from (values
  ('film', 'story', 'pos', 'Gripping', 'Positive'::public.sentiment, 0),
  ('film', 'story', 'neu', 'Uneven', 'Neutral'::public.sentiment, 1),
  ('film', 'story', 'neg', 'Weak', 'Negative'::public.sentiment, 2),
  ('film', 'acting', 'pos', 'Outstanding', 'Positive'::public.sentiment, 0),
  ('film', 'acting', 'neu', 'Serviceable', 'Neutral'::public.sentiment, 1),
  ('film', 'acting', 'neg', 'Disappointing', 'Negative'::public.sentiment, 2),
  ('film', 'music', 'pos', 'Memorable', 'Positive'::public.sentiment, 0),
  ('film', 'music', 'neu', 'Forgettable', 'Neutral'::public.sentiment, 1),
  ('film', 'music', 'neg', 'Grating', 'Negative'::public.sentiment, 2),
  ('film', 'visuals', 'pos', 'Stunning', 'Positive'::public.sentiment, 0),
  ('film', 'visuals', 'neu', 'Fine', 'Neutral'::public.sentiment, 1),
  ('film', 'visuals', 'neg', 'Flat', 'Negative'::public.sentiment, 2),
  ('film', 'value', 'pos', 'Yes, go', 'Positive'::public.sentiment, 0),
  ('film', 'value', 'neu', 'Wait for streaming', 'Neutral'::public.sentiment, 1),
  ('film', 'value', 'neg', 'Skip it', 'Negative'::public.sentiment, 2),
  ('series', 'writing', 'pos', 'Sharp', 'Positive'::public.sentiment, 0),
  ('series', 'writing', 'neu', 'Patchy', 'Neutral'::public.sentiment, 1),
  ('series', 'writing', 'neg', 'Weak', 'Negative'::public.sentiment, 2),
  ('series', 'pacing', 'pos', 'Tight', 'Positive'::public.sentiment, 0),
  ('series', 'pacing', 'neu', 'Slow in parts', 'Neutral'::public.sentiment, 1),
  ('series', 'pacing', 'neg', 'Drags badly', 'Negative'::public.sentiment, 2),
  ('series', 'cast', 'pos', 'Excellent', 'Positive'::public.sentiment, 0),
  ('series', 'cast', 'neu', 'Fine', 'Neutral'::public.sentiment, 1),
  ('series', 'cast', 'neg', 'Off', 'Negative'::public.sentiment, 2),
  ('series', 'ending', 'pos', 'Earned it', 'Positive'::public.sentiment, 0),
  ('series', 'ending', 'neu', 'Mixed', 'Neutral'::public.sentiment, 1),
  ('series', 'ending', 'neg', 'Fell apart', 'Negative'::public.sentiment, 2),
  ('brand', 'value', 'pos', 'Fair', 'Positive'::public.sentiment, 0),
  ('brand', 'value', 'neu', 'Borderline', 'Neutral'::public.sentiment, 1),
  ('brand', 'value', 'neg', 'Overpriced', 'Negative'::public.sentiment, 2),
  ('brand', 'quality', 'pos', 'Reliable', 'Positive'::public.sentiment, 0),
  ('brand', 'quality', 'neu', 'Inconsistent', 'Neutral'::public.sentiment, 1),
  ('brand', 'quality', 'neg', 'Poor', 'Negative'::public.sentiment, 2),
  ('brand', 'service', 'pos', 'Helpful', 'Positive'::public.sentiment, 0),
  ('brand', 'service', 'neu', 'Slow', 'Neutral'::public.sentiment, 1),
  ('brand', 'service', 'neg', 'Unhelpful', 'Negative'::public.sentiment, 2),
  ('brand', 'trust', 'pos', 'Yes', 'Positive'::public.sentiment, 0),
  ('brand', 'trust', 'neu', 'Unsure', 'Neutral'::public.sentiment, 1),
  ('brand', 'trust', 'neg', 'No', 'Negative'::public.sentiment, 2),
  ('sports', 'performance', 'pos', 'Excellent', 'Positive'::public.sentiment, 0),
  ('sports', 'performance', 'neu', 'Inconsistent', 'Neutral'::public.sentiment, 1),
  ('sports', 'performance', 'neg', 'Poor', 'Negative'::public.sentiment, 2),
  ('sports', 'leadership', 'pos', 'Sharp', 'Positive'::public.sentiment, 0),
  ('sports', 'leadership', 'neu', 'Mixed', 'Neutral'::public.sentiment, 1),
  ('sports', 'leadership', 'neg', 'Baffling', 'Negative'::public.sentiment, 2),
  ('sports', 'selection', 'pos', 'Fair', 'Positive'::public.sentiment, 0),
  ('sports', 'selection', 'neu', 'Debatable', 'Neutral'::public.sentiment, 1),
  ('sports', 'selection', 'neg', 'Indefensible', 'Negative'::public.sentiment, 2),
  ('sports', 'entertainment', 'pos', 'Thrilling', 'Positive'::public.sentiment, 0),
  ('sports', 'entertainment', 'neu', 'Watchable', 'Neutral'::public.sentiment, 1),
  ('sports', 'entertainment', 'neg', 'Dull', 'Negative'::public.sentiment, 2),
  ('sports', 'officiating', 'pos', 'Sound', 'Positive'::public.sentiment, 0),
  ('sports', 'officiating', 'neu', 'Inconsistent', 'Neutral'::public.sentiment, 1),
  ('sports', 'officiating', 'neg', 'Poor', 'Negative'::public.sentiment, 2),
  ('gadget', 'value', 'pos', 'Worth it', 'Positive'::public.sentiment, 0),
  ('gadget', 'value', 'neu', 'Borderline', 'Neutral'::public.sentiment, 1),
  ('gadget', 'value', 'neg', 'Overpriced', 'Negative'::public.sentiment, 2),
  ('gadget', 'build', 'pos', 'Premium', 'Positive'::public.sentiment, 0),
  ('gadget', 'build', 'neu', 'Ordinary', 'Neutral'::public.sentiment, 1),
  ('gadget', 'build', 'neg', 'Cheap', 'Negative'::public.sentiment, 2),
  ('gadget', 'performance', 'pos', 'Fast', 'Positive'::public.sentiment, 0),
  ('gadget', 'performance', 'neu', 'Adequate', 'Neutral'::public.sentiment, 1),
  ('gadget', 'performance', 'neg', 'Struggles', 'Negative'::public.sentiment, 2),
  ('gadget', 'battery', 'pos', 'All day', 'Positive'::public.sentiment, 0),
  ('gadget', 'battery', 'neu', 'Just about', 'Neutral'::public.sentiment, 1),
  ('gadget', 'battery', 'neg', 'Poor', 'Negative'::public.sentiment, 2),
  ('gadget', 'software', 'pos', 'Clean', 'Positive'::public.sentiment, 0),
  ('gadget', 'software', 'neu', 'Bloated but usable', 'Neutral'::public.sentiment, 1),
  ('gadget', 'software', 'neg', 'A mess', 'Negative'::public.sentiment, 2),
  ('platform', 'reliability', 'pos', 'Solid', 'Positive'::public.sentiment, 0),
  ('platform', 'reliability', 'neu', 'Occasional issues', 'Neutral'::public.sentiment, 1),
  ('platform', 'reliability', 'neg', 'Frequently broken', 'Negative'::public.sentiment, 2),
  ('platform', 'pricing', 'pos', 'Reasonable', 'Positive'::public.sentiment, 0),
  ('platform', 'pricing', 'neu', 'Getting steep', 'Neutral'::public.sentiment, 1),
  ('platform', 'pricing', 'neg', 'Unjustified', 'Negative'::public.sentiment, 2),
  ('platform', 'privacy', 'pos', 'Comfortable', 'Positive'::public.sentiment, 0),
  ('platform', 'privacy', 'neu', 'Unsure', 'Neutral'::public.sentiment, 1),
  ('platform', 'privacy', 'neg', 'Not comfortable', 'Negative'::public.sentiment, 2),
  ('platform', 'support', 'pos', 'Yes', 'Positive'::public.sentiment, 0),
  ('platform', 'support', 'neu', 'Eventually', 'Neutral'::public.sentiment, 1),
  ('platform', 'support', 'neg', 'No', 'Negative'::public.sentiment, 2),
  ('event', 'organisation', 'pos', 'Well run', 'Positive'::public.sentiment, 0),
  ('event', 'organisation', 'neu', 'Rough edges', 'Neutral'::public.sentiment, 1),
  ('event', 'organisation', 'neg', 'Badly run', 'Negative'::public.sentiment, 2),
  ('event', 'safety', 'pos', 'Handled well', 'Positive'::public.sentiment, 0),
  ('event', 'safety', 'neu', 'Some concerns', 'Neutral'::public.sentiment, 1),
  ('event', 'safety', 'neg', 'Serious lapses', 'Negative'::public.sentiment, 2),
  ('event', 'coverage', 'pos', 'Fair', 'Positive'::public.sentiment, 0),
  ('event', 'coverage', 'neu', 'Patchy', 'Neutral'::public.sentiment, 1),
  ('event', 'coverage', 'neg', 'Distorted', 'Negative'::public.sentiment, 2),
  ('event', 'impact', 'pos', 'Significant', 'Positive'::public.sentiment, 0),
  ('event', 'impact', 'neu', 'Some', 'Neutral'::public.sentiment, 1),
  ('event', 'impact', 'neg', 'None', 'Negative'::public.sentiment, 2),
  ('national-politics', 'direction', 'pos', 'Right direction', 'Positive'::public.sentiment, 0),
  ('national-politics', 'direction', 'neu', 'Too early to say', 'Neutral'::public.sentiment, 1),
  ('national-politics', 'direction', 'neg', 'Wrong direction', 'Negative'::public.sentiment, 2),
  ('national-politics', 'economy', 'pos', 'Competent', 'Positive'::public.sentiment, 0),
  ('national-politics', 'economy', 'neu', 'Mixed', 'Neutral'::public.sentiment, 1),
  ('national-politics', 'economy', 'neg', 'Mishandled', 'Negative'::public.sentiment, 2),
  ('national-politics', 'transparency', 'pos', 'Open', 'Positive'::public.sentiment, 0),
  ('national-politics', 'transparency', 'neu', 'Partial', 'Neutral'::public.sentiment, 1),
  ('national-politics', 'transparency', 'neg', 'Opaque', 'Negative'::public.sentiment, 2),
  ('national-politics', 'tone', 'pos', 'Constructive', 'Positive'::public.sentiment, 0),
  ('national-politics', 'tone', 'neu', 'Noisy', 'Neutral'::public.sentiment, 1),
  ('national-politics', 'tone', 'neg', 'Toxic', 'Negative'::public.sentiment, 2),
  ('policy', 'intent', 'pos', 'Sound', 'Positive'::public.sentiment, 0),
  ('policy', 'intent', 'neu', 'Mixed', 'Neutral'::public.sentiment, 1),
  ('policy', 'intent', 'neg', 'Misguided', 'Negative'::public.sentiment, 2),
  ('policy', 'implementation', 'pos', 'Well executed', 'Positive'::public.sentiment, 0),
  ('policy', 'implementation', 'neu', 'Uneven', 'Neutral'::public.sentiment, 1),
  ('policy', 'implementation', 'neg', 'Botched', 'Negative'::public.sentiment, 2),
  ('policy', 'beneficiaries', 'pos', 'Most people', 'Positive'::public.sentiment, 0),
  ('policy', 'beneficiaries', 'neu', 'A narrow group', 'Neutral'::public.sentiment, 1),
  ('policy', 'beneficiaries', 'neg', 'Almost nobody', 'Negative'::public.sentiment, 2),
  ('policy', 'clarity', 'pos', 'Clear', 'Positive'::public.sentiment, 0),
  ('policy', 'clarity', 'neu', 'Confusing', 'Neutral'::public.sentiment, 1),
  ('policy', 'clarity', 'neg', 'Not explained', 'Negative'::public.sentiment, 2),
  ('policy', 'timing', 'pos', 'Right time', 'Positive'::public.sentiment, 0),
  ('policy', 'timing', 'neu', 'Debatable', 'Neutral'::public.sentiment, 1),
  ('policy', 'timing', 'neg', 'Wrong time', 'Negative'::public.sentiment, 2),
  ('politician', 'integrity', 'pos', 'Trust them', 'Positive'::public.sentiment, 0),
  ('politician', 'integrity', 'neu', 'Unsure', 'Neutral'::public.sentiment, 1),
  ('politician', 'integrity', 'neg', 'Do not trust them', 'Negative'::public.sentiment, 2),
  ('politician', 'delivery', 'pos', 'Largely', 'Positive'::public.sentiment, 0),
  ('politician', 'delivery', 'neu', 'Partly', 'Neutral'::public.sentiment, 1),
  ('politician', 'delivery', 'neg', 'Barely', 'Negative'::public.sentiment, 2),
  ('politician', 'communication', 'pos', 'Clear', 'Positive'::public.sentiment, 0),
  ('politician', 'communication', 'neu', 'Guarded', 'Neutral'::public.sentiment, 1),
  ('politician', 'communication', 'neg', 'Evasive', 'Negative'::public.sentiment, 2),
  ('politician', 'accessibility', 'pos', 'Present', 'Positive'::public.sentiment, 0),
  ('politician', 'accessibility', 'neu', 'Occasionally', 'Neutral'::public.sentiment, 1),
  ('politician', 'accessibility', 'neg', 'Absent', 'Negative'::public.sentiment, 2),
  ('college', 'teaching', 'pos', 'Strong', 'Positive'::public.sentiment, 0),
  ('college', 'teaching', 'neu', 'Uneven', 'Neutral'::public.sentiment, 1),
  ('college', 'teaching', 'neg', 'Weak', 'Negative'::public.sentiment, 2),
  ('college', 'placements', 'pos', 'Match it', 'Positive'::public.sentiment, 0),
  ('college', 'placements', 'neu', 'Below reputation', 'Neutral'::public.sentiment, 1),
  ('college', 'placements', 'neg', 'Far below', 'Negative'::public.sentiment, 2),
  ('college', 'facilities', 'pos', 'Good', 'Positive'::public.sentiment, 0),
  ('college', 'facilities', 'neu', 'Adequate', 'Neutral'::public.sentiment, 1),
  ('college', 'facilities', 'neg', 'Poor', 'Negative'::public.sentiment, 2),
  ('college', 'fees', 'pos', 'Justified', 'Positive'::public.sentiment, 0),
  ('college', 'fees', 'neu', 'Steep', 'Neutral'::public.sentiment, 1),
  ('college', 'fees', 'neg', 'Unjustifiable', 'Negative'::public.sentiment, 2),
  ('college', 'culture', 'pos', 'Supportive', 'Positive'::public.sentiment, 0),
  ('college', 'culture', 'neu', 'Mixed', 'Neutral'::public.sentiment, 1),
  ('college', 'culture', 'neg', 'Draining', 'Negative'::public.sentiment, 2),
  ('exam', 'difficulty', 'pos', 'Fair', 'Positive'::public.sentiment, 0),
  ('exam', 'difficulty', 'neu', 'Uneven', 'Neutral'::public.sentiment, 1),
  ('exam', 'difficulty', 'neg', 'Unfair', 'Negative'::public.sentiment, 2),
  ('exam', 'conduct', 'pos', 'Clean', 'Positive'::public.sentiment, 0),
  ('exam', 'conduct', 'neu', 'Some concerns', 'Neutral'::public.sentiment, 1),
  ('exam', 'conduct', 'neg', 'Compromised', 'Negative'::public.sentiment, 2),
  ('exam', 'results', 'pos', 'On time', 'Positive'::public.sentiment, 0),
  ('exam', 'results', 'neu', 'Delayed', 'Neutral'::public.sentiment, 1),
  ('exam', 'results', 'neg', 'Badly mishandled', 'Negative'::public.sentiment, 2),
  ('exam', 'syllabus', 'pos', 'Matched', 'Positive'::public.sentiment, 0),
  ('exam', 'syllabus', 'neu', 'Partly', 'Neutral'::public.sentiment, 1),
  ('exam', 'syllabus', 'neg', 'Out of syllabus', 'Negative'::public.sentiment, 2),
  ('exam', 'grievance', 'pos', 'Addressed', 'Positive'::public.sentiment, 0),
  ('exam', 'grievance', 'neu', 'Slow', 'Neutral'::public.sentiment, 1),
  ('exam', 'grievance', 'neg', 'Ignored', 'Negative'::public.sentiment, 2),
  ('career', 'roi', 'pos', 'Worth it', 'Positive'::public.sentiment, 0),
  ('career', 'roi', 'neu', 'Marginal', 'Neutral'::public.sentiment, 1),
  ('career', 'roi', 'neg', 'Not worth it', 'Negative'::public.sentiment, 2),
  ('career', 'demand', 'pos', 'Strong', 'Positive'::public.sentiment, 0),
  ('career', 'demand', 'neu', 'Softening', 'Neutral'::public.sentiment, 1),
  ('career', 'demand', 'neg', 'Weak', 'Negative'::public.sentiment, 2),
  ('career', 'quality', 'pos', 'Genuinely useful', 'Positive'::public.sentiment, 0),
  ('career', 'quality', 'neu', 'Some of it', 'Neutral'::public.sentiment, 1),
  ('career', 'quality', 'neg', 'Little of it', 'Negative'::public.sentiment, 2),
  ('career', 'worklife', 'pos', 'Sustainable', 'Positive'::public.sentiment, 0),
  ('career', 'worklife', 'neu', 'Demanding', 'Neutral'::public.sentiment, 1),
  ('career', 'worklife', 'neg', 'Punishing', 'Negative'::public.sentiment, 2),
  ('career', 'advice', 'pos', 'Yes', 'Positive'::public.sentiment, 0),
  ('career', 'advice', 'neu', 'With caveats', 'Neutral'::public.sentiment, 1),
  ('career', 'advice', 'neg', 'No', 'Negative'::public.sentiment, 2),
  ('food', 'taste', 'pos', 'Excellent', 'Positive'::public.sentiment, 0),
  ('food', 'taste', 'neu', 'Fine', 'Neutral'::public.sentiment, 1),
  ('food', 'taste', 'neg', 'Poor', 'Negative'::public.sentiment, 2),
  ('food', 'value', 'pos', 'Worth it', 'Positive'::public.sentiment, 0),
  ('food', 'value', 'neu', 'Steep', 'Neutral'::public.sentiment, 1),
  ('food', 'value', 'neg', 'Overpriced', 'Negative'::public.sentiment, 2),
  ('food', 'consistency', 'pos', 'Reliable', 'Positive'::public.sentiment, 0),
  ('food', 'consistency', 'neu', 'Variable', 'Neutral'::public.sentiment, 1),
  ('food', 'consistency', 'neg', 'Unpredictable', 'Negative'::public.sentiment, 2),
  ('food', 'hygiene', 'pos', 'Clean', 'Positive'::public.sentiment, 0),
  ('food', 'hygiene', 'neu', 'Passable', 'Neutral'::public.sentiment, 1),
  ('food', 'hygiene', 'neg', 'Concerning', 'Negative'::public.sentiment, 2),
  ('food', 'return', 'pos', 'Yes', 'Positive'::public.sentiment, 0),
  ('food', 'return', 'neu', 'Maybe', 'Neutral'::public.sentiment, 1),
  ('food', 'return', 'neg', 'No', 'Negative'::public.sentiment, 2),
  ('place', 'experience', 'pos', 'Worth the trip', 'Positive'::public.sentiment, 0),
  ('place', 'experience', 'neu', 'Fine, not special', 'Neutral'::public.sentiment, 1),
  ('place', 'experience', 'neg', 'Not worth it', 'Negative'::public.sentiment, 2),
  ('place', 'value', 'pos', 'Fair', 'Positive'::public.sentiment, 0),
  ('place', 'value', 'neu', 'Steep', 'Neutral'::public.sentiment, 1),
  ('place', 'value', 'neg', 'A rip-off', 'Negative'::public.sentiment, 2),
  ('place', 'crowding', 'pos', 'Comfortable', 'Positive'::public.sentiment, 0),
  ('place', 'crowding', 'neu', 'Busy but bearable', 'Neutral'::public.sentiment, 1),
  ('place', 'crowding', 'neg', 'Ruined by crowds', 'Negative'::public.sentiment, 2),
  ('place', 'upkeep', 'pos', 'Well kept', 'Positive'::public.sentiment, 0),
  ('place', 'upkeep', 'neu', 'Tired in places', 'Neutral'::public.sentiment, 1),
  ('place', 'upkeep', 'neg', 'Neglected', 'Negative'::public.sentiment, 2),
  ('place', 'access', 'pos', 'Easy', 'Positive'::public.sentiment, 0),
  ('place', 'access', 'neu', 'Some hassle', 'Neutral'::public.sentiment, 1),
  ('place', 'access', 'neg', 'A struggle', 'Negative'::public.sentiment, 2),
  ('place', 'return', 'pos', 'Yes', 'Positive'::public.sentiment, 0),
  ('place', 'return', 'neu', 'Once was enough', 'Neutral'::public.sentiment, 1),
  ('place', 'return', 'neg', 'No', 'Negative'::public.sentiment, 2),
  ('controversy', 'credibility', 'pos', 'Credible', 'Positive'::public.sentiment, 0),
  ('controversy', 'credibility', 'neu', 'Unproven', 'Neutral'::public.sentiment, 1),
  ('controversy', 'credibility', 'neg', 'Overblown', 'Negative'::public.sentiment, 2),
  ('controversy', 'response', 'pos', 'Adequate', 'Positive'::public.sentiment, 0),
  ('controversy', 'response', 'neu', 'Slow', 'Neutral'::public.sentiment, 1),
  ('controversy', 'response', 'neg', 'Evasive', 'Negative'::public.sentiment, 2),
  ('controversy', 'media', 'pos', 'Proportionate', 'Positive'::public.sentiment, 0),
  ('controversy', 'media', 'neu', 'Uneven', 'Neutral'::public.sentiment, 1),
  ('controversy', 'media', 'neg', 'Sensationalised', 'Negative'::public.sentiment, 2),
  ('controversy', 'accountability', 'pos', 'Yes', 'Positive'::public.sentiment, 0),
  ('controversy', 'accountability', 'neu', 'Partially', 'Neutral'::public.sentiment, 1),
  ('controversy', 'accountability', 'neg', 'No', 'Negative'::public.sentiment, 2),
  ('general', 'quality', 'pos', 'Good', 'Positive'::public.sentiment, 0),
  ('general', 'quality', 'neu', 'Mixed', 'Neutral'::public.sentiment, 1),
  ('general', 'quality', 'neg', 'Poor', 'Negative'::public.sentiment, 2),
  ('general', 'value', 'pos', 'Worth it', 'Positive'::public.sentiment, 0),
  ('general', 'value', 'neu', 'Borderline', 'Neutral'::public.sentiment, 1),
  ('general', 'value', 'neg', 'Not worth it', 'Negative'::public.sentiment, 2),
  ('general', 'trust', 'pos', 'Yes', 'Positive'::public.sentiment, 0),
  ('general', 'trust', 'neu', 'Unsure', 'Neutral'::public.sentiment, 1),
  ('general', 'trust', 'neg', 'No', 'Negative'::public.sentiment, 2),
  ('general', 'recommend', 'pos', 'Yes', 'Positive'::public.sentiment, 0),
  ('general', 'recommend', 'neu', 'With caveats', 'Neutral'::public.sentiment, 1),
  ('general', 'recommend', 'neg', 'No', 'Negative'::public.sentiment, 2)
) as v(set_id, facet_key, key, label, tone, position)
join public.facet_set_facets f on f.set_id = v.set_id and f.key = v.facet_key
on conflict (facet_id, key) do update set
  label = excluded.label,
  tone = excluded.tone,
  position = excluded.position;
